开始吧
-------

Python菜鸟? 来，先教你如何正确配置Python环境。

.. toctree::
   :maxdepth: 2

   starting/which-python

- 如何正确地安装Python

 .. toctree::
    :maxdepth: 1

    starting/installation
    starting/install/osx
    starting/install/win
    starting/install/linux



写出优雅的代码
---------------

本章主要聚焦于编写Python代码的最佳实践。

.. toctree::
   :maxdepth: 2

   writing/structure
   writing/style
   writing/reading
   writing/documentation
   writing/tests
   writing/logging
   writing/gotchas
   writing/license



Python应用场景
---------------

本章主要聚焦于不同场景下工具和模块的使用建议。

.. toctree::
   :maxdepth: 2

   scenarios/client
   scenarios/web
   scenarios/scrape
   scenarios/cli
   scenarios/gui
   scenarios/db
   scenarios/network
   scenarios/admin
   scenarios/ci
   scenarios/speed
   scenarios/scientific
   scenarios/imaging
   scenarios/serialization
   scenarios/xml
   scenarios/json
   scenarios/crypto
   scenarios/clibs


Python代码打包
---------------

本章主要聚焦于Python代码的部署。

.. toctree::
   :maxdepth: 2

   shipping/packaging
   shipping/freezing


Python开发环境
---------------

本章主要聚焦于Python的开发环境以及编写Python代码工具的最佳实践。

.. toctree::
   :maxdepth: 2

   dev/env
   dev/virtualenvs
   dev/pip-virtualenv




附加说明
---------

本章内容比较单调，先介绍一些关于Python的背景，然后聚焦于接下来的内容。


.. toctree::
   :maxdepth: 2

   intro/duction
   intro/community
   intro/learning
   intro/documentation
   intro/news

.. note::
   所有的全音阶和半音音阶中定义的注意事项已经有意从附加说明这个名单中排除。除了此说明。


--------------------------------------

贡献说明以及法律信息（给那些感兴趣的人）。

.. toctree::
   :maxdepth: 2

   notes/contribute
   notes/license
   notes/styleguide